---
id: ulaform
name: Ulaform
full: HTML form generation and processing application
description: >-
  Ulaform is a PHP-based dynamic HTML form creation and generation system.
  Ulaform allows users to create sophisticated forms using a web browser, and
  then render the forms within other web pages by a simple PHP include, or in
  other Horde applications through the Horde Block API.
list: horde
type: application
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 1.0.0alpha2
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl.php
dependencies:
  required:
    php: ^7
    composer:
      horde/horde: ^6
      horde/Core: ^3
      horde/db: ^3
